"use client";
// import type { Metadata } from "next";
import "primeicons/primeicons.css";
import "primereact/resources/primereact.min.css";
import "./globals.css";
import "primereact/resources/themes/lara-light-indigo/theme.css";
import { ArticlesProvider } from "./contexts/articlesContext";
import { Poppins } from "next/font/google";
import { AuthContextProvider } from "./contexts/authContext";

const poppins = Poppins({
  weight: ["400", "700", "600"],
  style: ["normal"],
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <AuthContextProvider>
          <ArticlesProvider>{children}</ArticlesProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
