"use client";
// import type { Metadata } from "next";
import "primeicons/primeicons.css";
import "primereact/resources/primereact.min.css";
import "./globals.css";
import "primereact/resources/themes/lara-light-blue/theme.css";
import { ArticlesProvider } from "./contexts/articlesContext";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ArticlesProvider>{children}</ArticlesProvider>
      </body>
    </html>
  );
}
